@echo off
echo Adding Firebase resources to GCP project...
call npx firebase-tools projects:addfirebase areyousafe-prod
echo Creating hosting site...
call npx firebase-tools hosting:sites:create areyousafe-prod --project areyousafe-prod
echo Deploying...
call npx firebase-tools deploy --only hosting --project areyousafe-prod
